### ISSUE TITLE
Unknown Method Curl_reset() on php5.4

### ISSUE THREAD

**Issue by justinParton** [Bluhex/october-youtube#4]
Installed the package and ran it only to find that this error:

**Call to undefined function GuzzleHttp\Handler\curl_reset()**
_/home/content/28/2439128/html/new_gbfic/plugins/bluhex/youtube/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 78_

Evidently that method is only available on php5.5, which may not be possible if on a shared hosting that hasnt updated php yet.

**Comment by BrendonPark** [comment]
I'm listing this as won't fix for a few reasons:
- PHP 5.4 support ended in September 2015.
- PHP 5.5 is now required for the latest versions of October CMS.
- The dependency required to be compatible with 5.4 is no longer being developed.
